name: Send emails
on:
  schedule:
    - cron: '0 23 * * 2'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'read_worksheet'
        uses: jroehl/gsheet.action@v2.0.1 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId:  ${{ secrets.GSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData", "args": { "range": "'Schedule'!A2:B" }},
              { "command": "getData", "args": { "range": "'List'!C2:C" }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Get moderator
        env:
          RESULTS: ${{ steps.read_worksheet.outputs.results }}
        run: |
          echo "NextTuesday=$(date '+%b %-d' -d "next tuesday")" >> $GITHUB_ENV
          echo "MODERATOR=$(echo "$RESULTS" | jq -r --arg nT "$(date '+%b %-d, %Y' -d "next tuesday")" '.results | .[0].result.rawData | .[] | select(.[0]==$nT) | .[1]')" >> $GITHUB_ENV
          echo "N1_MODERATOR=$(echo "$RESULTS" | jq -r --arg n1T "$(date '+%b %-d, %Y' -d "1 week next tuesday")" '.results | .[0].result.rawData | .[] | select(.[0]==$n1T) | "\(.[0])    \(.[1])"')" >> $GITHUB_ENV
          echo "N2_MODERATOR=$(echo "$RESULTS" | jq -r --arg n2T "$(date '+%b %-d, %Y' -d "2 week next tuesday")" '.results | .[0].result.rawData | .[] | select(.[0]==$n2T) | "\(.[0])    \(.[1])"')" >> $GITHUB_ENV
          echo "N3_MODERATOR=$(echo "$RESULTS" | jq -r --arg n3T "$(date '+%b %-d, %Y' -d "3 week next tuesday")" '.results | .[0].result.rawData | .[] | select(.[0]==$n3T) | "\(.[0])    \(.[1])"')" >> $GITHUB_ENV
          echo "EMAILS=$(echo "$RESULTS" | jq -r '.results | .[1].result.rawData | .[] | .[0] ' | sed -e :a -e '$!N; s/\n/, /; ta')" >> $GITHUB_ENV
      # - name: Read back into Github environment
      #   run: |
      #     echo $MODERATOR
      #     echo $EMAILS
      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Journal Club: Tue ${{env.NextTuesday}} 2pm-3pm. Moderator: ${{env.MODERATOR}}"
          body: "Hi all,\n\nNext journal club meeting is on ${{env.NextTuesday}} from 2pm to 3pm. The next scheduled moderator, ${{env.MODERATOR}}, please select a paper and reply all to this email by Thursday.\n\nNext moderators:\n${{env.N1_MODERATOR}}\n${{env.N2_MODERATOR}}\n${{env.N3_MODERATOR}}\n\nPlease exchange turns if you can not make it to the week you are scheduled to be the moderator.\n\n${{secrets.ZOOM_DETAILS}}\n\nThanks,\nSPJC Mailer\n\nP.S. For more information: https://github.com/anchal-physics/SPJC/wiki\n"
          to: ${{env.EMAILS}}
          from: SPJC Mailer